using System.Text.Json.Serialization;
using Blazored.LocalStorage;
using Blazored.Modal;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using MudBlazor.Services;
using StudyBuddy.WebUi;
using StudyBuddy.WebUi.Utils;
using Syncfusion.Blazor;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.Services.AddScoped(sp=> new HttpClient {  });
builder.RootComponents.Add<HeadOutlet>("head::after");
builder.Services.AddScoped<ModalManager>();
builder.Services.AddBlazoredModal();
builder.Services.AddBlazoredLocalStorage();
builder.Services.AddAuthorizationCore();
builder.Services.AddScoped<AuthenticationStateProvider,AuthStateProvider>();
builder.Services.AddScoped(sp => new HttpClient ());
builder.Services.AddMudServices();
await builder.Build().RunAsync();
